#!/bin/bash
#ddev-generated
## Description: Launch behat tests with video recording
## Usage: behat-video <environment> <behat_args>
## Aliases: behat-video, behat-v, bv
## Example: "ddev behat-video local"

#Enable video profile
ddev start --profiles selenium-video

# Run behat tests with parameters
ddev behat "$@"

# Restart ddev to disable video profile
ddev restart
echo "All tests were recorded. You can find the videos in the ${DDEV_APPROOT}/reports/videos directory."
